local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: mmtr/odom # Should this be here
    robot_base_frame: base_footprint ##Base footprint?
    rolling_window: true
    width: 8
    height: 8
    resolution: 0.05
    update_frequency: 10.0
    publish_frequency: 5.0
    plugins:
      - {name: static_layer,    type: "nav2_costmap_2d::StaticLayer"}
      - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}
    static_layer:
      map_topic: /map
      subscribe_to_updates: true
      track_unknown_space: true
      map_subscribe_transient_local: false   # <-- IMPORTANT for your mapper
    inflation_layer:
      inflation_radius: 0.4
      cost_scaling_factor: 3.0